### ISSUE TITLE
Placeholders with Timelines behave incorrectly in Embedded Presentations

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#826] opened 2019-11-05 23:30 UTC
**Describe the bug**
Placeholders that are overlapped and have different timelines in a presentation do not behave correctly when their presentation is embedded using the Embedded Presentations widget.

For instance, only the topmost placeholder will show content, while the placeholders underneath it will not appear at all, even when the topmost placeholder is not visible.

**Reach**
This would affect any user trying to schedule multiple placeholders in a stack inside an embedded presentation using Editor.  This does not affect our templates.

**Impact**
You can achieve the same result by breaking the Placeholders out into their own Presentations, and scheduling the Embedded Presentations widget to follow your timeline.

**To Reproduce**
1. Create a presentation from a Blank canvas.
2. Create two full-screen placeholders, and place them both from position 0,0 so they overlap completely.
3. Set timelines so that they should appear at different times, i.e. ph0 from 8:00am-9:00am and ph1 from 9:00am-10:00am.
4. Set content inside each of the placeholders.
5. Create a second presentation from a Blank canvas.
6. Create a full-screen placeholder, and use the Embedded Presentations widget to play the presentation you created in step 1.

Running the presentation you built in Step 1 on a Display should show either placeholder at their correct times.
Running the presentation you built in Step 6 should only show one of the placeholders, and the rest of the time the content is invisible.

**Expected behavior**
Behavior should be consistent whether or not a Presentation is embedded;  Placeholder timelines should be followed by Player.

**Screenshots**
N/A, I'll link a video in the Trello card.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by alex-deaconu** [comment] 2019-11-06 16:30
As discussed, this is intended behaviour, however it is not very intuitive as to why this is happening.

Basically, the first Placeholder acts as the PUD Placeholder. If that Placeholder is set to not play because of Timeline restrictions, the whole Presentation will not play.

Suggested a workaround of adding a separate PUD Placeholder so that behaviour is ignored.

We could improve the behaviour, however it is not recommended because there may be content out there relying on things to behave in this manner.

Closing. Thanks!

**Closed by alex-deaconu** 2019-11-06 16:30 UTC

**Comment by sheadarlison** [comment] 2019-11-06 16:33
@alex-deaconu does the first placeholder act as the PUD Placeholder even if the PUD Placeholder isn't configured in the Presentation settings? https://www.screencast.com/t/CGuaRXTQdgzZ

**Comment by alex-deaconu** [comment] 2019-11-06 16:44
@sheadarlison unfortunately yes. It defaults to the first placeholder if the value is blank. Again, not very intuitive and not sure how well documented this is. Thanks.

**Comment by sheadarlison** [comment] 2019-11-06 20:15
Interesting thanks
