### ISSUE TITLE
HTML Templates behave inconsistently while player is offline

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-launcher-electron#809] opened 2019-08-26 20:15 UTC
**Describe the bug**
Behavior of HTML templates when player is running offline is inconsistent;
- Added only Recycling template, it worked while Online but was a white screen when player was launched Offline.
- Added the Image Template with 1 image to the same schedule.  Both worked while online.  When player was launched offline, only the Recycling template worked, the other was a white screen.
- Removed the Image Template, Recycling worked while online and worked when player was launched Offline.
- Re-added the Image Template with 1 image to the same schedule.  Both worked while online.  When player was launched offline, both Templates loaded, but Image Template only plays for a split second.

**Reach**
This might affect anyone who tries to start Rise Player while offline.

**Impact**
Player behaves as expected when it's connected to the Internet.  There's no known workaround while offline.

**To Reproduce**
1. Create a schedule with 1 HTML Template such as the Recycling template.
2. Play it on your Display so the content caches.
3. Close Rise Player with Ctrl + Shift + Q.
4. Disconnect your player from the Internet.
5. Open Rise Player.

**Expected behavior**
HTML templates play content offline without issue, with the exception that updates and dynamic content aren't received.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Additional context**
N/A

**Comment by olegrise** [comment] 2019-09-09 15:41
Issue was caused by the logic in the Common Template code that checked for the origin of the DOM messages and blocked the event if origin is not "risevision.com". This prevent Play Until Done functionality from working properly in offline mode. Issue if fixed now. Thanks.

**Comment by stulees** [comment] 2019-09-19 19:22
This has now been fixed with Viewer changes in https://github.com/Rise-Vision/viewer/pull/330 and _rise-image_ component changes in https://github.com/Rise-Vision/rise-image/pull/49 .

**Closed by stulees** 2019-09-19 19:22 UTC
Labels: bug
